# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/e800f052-abeb-4a63-8748-6eb070f166d5";
  #     fsType = "ext4";
  #   };

  fileSystems."/" = {
    fsType = "zfs";
    device = "zroot";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/disk-main-ESP"; # must match path generated by disko
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/36390041-e187-497f-a691-e5050c83550a"; }
  #   ];
  swapDevices = [ ];

  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  networking.hostId = "2340af4c"; # head -c 8 /etc/machine-id

  networking = {
    enableIPv6 = true;
    useDHCP = false;

    interfaces = {
      ens18.ipv4.addresses = [{
        address = "77.90.16.190";
        prefixLength = 32;
      }];
      ens18.ipv6.addresses = [{
        address = "2a0f:6284:4300:101::8";
        prefixLength = 64;
      }];
    };
    defaultGateway = {
      address = "77.90.16.1";
      interface = "ens18";
    };
    defaultGateway6 = {
      address = "fe80::1";
      interface = "ens18";
    };
    nameservers = ["1.1.1.1" "8.8.8.8"];
  };
}
