name: Deploy

on:
  push:
    branches:
    - stable
  workflow_dispatch:

jobs:
  deploy:
    environment: server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/determinate-nix-action@v3.13.2
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: push new config
      run: nix run .#colmena -- apply --on pawhost-next
